abi/sector_test.go

Follow up spun off from integrating into specs actors that I missed while reviewing the first transfer.  Pure copy paste of tests to cover functions that now live here

Add sector test

---

abi/sector.go

I forgot to push this commit into #1.

Add PoStSealProofTypes

---

crypto/randomness.go
crypto/signature.go
crypto/signature_test.go
exitcode/common.go
exitcode/exitcode.go
exitcode/exitcode_test.go
exitcode/reserved.go

Copies the crypto and exitcode packages out from specs-actors, since we don't expect to version these with a release-branch approach.
FYI @arajasek @magik6k @raulk

Add crypto and exitcode

---

network/version.go

Describe versions 7 and 8, add 10

---

abi/sector.go
go.sum

Add aggregation proof type

---

network/version.go

Actually merge what the lotus depends on

---

exitcode/common.go
exitcode/reserved.go

Ported from:
- https://github.com/filecoin-project/ref-fvm/blob/17e5a31cee866da7045272d6f99a4b9a7d53a94e/shared/src/error/mod.rs#L64
- https://github.com/filecoin-project/ref-fvm/blob/17e5a31cee866da7045272d6f99a4b9a7d53a94e/shared/src/error/mod.rs#L77
- https://github.com/filecoin-project/ref-fvm/blob/17e5a31cee866da7045272d6f99a4b9a7d53a94e/shared/src/error/mod.rs#L100-L104

fix: add missing FVM exitcode (4, 11 , and 22-24)

---

builtin/methods.go

This is the only change needed in this repo to support FIP-0044.
resolves #60

FIP-0044: Add AuthenticateMessage method num

---

Makefile
builtin/v9/gen/gen.go
builtin/v9/miner/cbor_gen.go
builtin/v9/miner/miner_state.go
builtin/v9/miner/miner_types.go

These state changes should match up with https://github.com/filecoin-project/builtin-actors/pull/496/files

Add miner state to v9 needed for FIP-0029

---

builtin/v9/migration/miner.go
builtin/v9/migration/test/miner_test.go

Closes https://github.com/filecoin-project/go-state-types/issues/55
The specification for the change can be found [here](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0029.md), and the Rust-based implementation can be found [here](https://github.com/filecoin-project/builtin-actors/pull/496/files).

feat: migration for FIP-0029

---

abi/key.go
builtin/methods.go
builtin/v8/market/deal_test.go
builtin/v9/account/methods.go
builtin/v9/datacap/datacap_state.go
builtin/v9/gen/gen.go
builtin/v9/market/cbor_gen.go
builtin/v9/market/deal.go
builtin/v9/market/market_state.go
builtin/v9/market/market_types.go
builtin/v9/migration/miner.go
builtin/v9/miner/cbor_gen.go
builtin/v9/miner/methods.go
builtin/v9/miner/miner_state.go
builtin/v9/miner/miner_types.go
builtin/v9/multisig/methods.go
builtin/v9/verifreg/cbor_gen.go
builtin/v9/verifreg/methods.go
builtin/v9/verifreg/policy.go
builtin/v9/verifreg/verified_registry_state.go
builtin/v9/verifreg/verifreg_types.go

Closes https://github.com/filecoin-project/go-state-types/issues/57, https://github.com/filecoin-project/go-state-types/issues/72,  https://github.com/filecoin-project/go-state-types/issues/73, https://github.com/filecoin-project/go-state-types/issues/74, https://github.com/filecoin-project/go-state-types/issues/75

feat: Integrate FIP-0045 changes into verifreg, miner, market

---

builtin/v9/account/cbor_gen.go
builtin/v9/gen/gen.go
builtin/v9/power/cbor_gen.go

AuthenticateMessageParams and CreateMinerParams
fixes #106

fix: implement cbor for remaining methods

---

builtin/v10/migration/top.go

Correctly set old code CIDs in the migrations map.
Also propagate all errors to avoid any confusion.

Migration: fix barebones skeleton

---

builtin/methods.go
builtin/v10/placeholder/methods.go
manifest/manifest.go

https://github.com/filecoin-project/builtin-actors/pull/978

rename embryo to placeholder 

---

builtin/v10/eam/cbor_gen.go
builtin/v10/gen/gen.go

Or else they get no unmarshaller... sigh

make gen for eam.CreateExternalReturn

---

builtin/methods.go
builtin/v10/ethaccount/methods.go
builtin/v10/ethaccount/types.go

c.f. https://github.com/filecoin-project/builtin-actors/pull/1071

EthAccount: Add new FIP-0044 methods

---

exitcode/common.go
exitcode/reserved.go

This syncs the exit codes with the latest ones used by the FVM.

fix: update exit codes

---

builtin/methods.go
builtin/v10/init/methods.go

relevant fvm PR https://github.com/filecoin-project/builtin-actors/pull/1179

FIP-0050: Init actor: Do not export the Exec method

---

builtin/methods.go
builtin/v10/account/methods.go

see https://github.com/filecoin-project/go-state-types/pull/163 - following up and removing UniversalReceiverHook from additional places

remove UniversalReceiverHook from go-state-types to match rust

---

builtin/network.go

Corresponds to https://github.com/filecoin-project/builtin-actors/blob/45c56ed57190349f1856d3258af6c09a24ea1395/runtime/src/runtime/policy.rs#L389

Add EndOfLifeClaimDropPeriod

---

builtin/v10/gen/gen.go
builtin/v10/market/cbor_gen.go
builtin/v11/gen/gen.go
builtin/v11/market/cbor_gen.go

Reported by `terry.hung` on the Filecoin Slack.

fix: market: add missing types to cbor-gen

---

actors/version.go

Map network version 20 to actors version 11

---

builtin/v10/verifreg/verified_registry_state.go
builtin/v11/verifreg/verified_registry_state.go
builtin/v9/verifreg/verified_registry_state.go

Also chain errors where missing.

refactor: verified registry: don't error if map entry isn't found

---

builtin/v11/market/policy.go
builtin/v11/migration/miner.go
builtin/v11/migration/top.go
builtin/v11/miner/cbor_gen.go
builtin/v11/miner/miner_state.go
builtin/v11/miner/policy.go

This reverts commit d86ac8c182881a81f16f472d3b46dce0e2ba22ae.

Revert "feat: sector migration for nv19 (#176)"

---

builtin/v12/migration/miner.go

Reverts filecoin-project/go-state-types#199
Part of https://github.com/filecoin-project/go-state-types/issues/203

Revert "Migrate deadlines using diff"

---

builtin/v12/migration/miner.go

This was copy-pastad from the v11 migration in #195 
I _think_ this closes #197.

fix: nv12 migration: drop MinerInfo migration

---

builtin/v12/miner/policy.go

As in https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0052.md.

feat: implement FIP-0052

---

builtin/v12/miner/policy.go

Integrates https://github.com/filecoin-project/builtin-actors/pull/1436.

feat: limit PoSted partitions to 3

---

builtin/v12/miner/invariants.go

Unfortunately, this is the only invariant I can think of based on looking at the SectorInfo alone. Would love additional ideas.

feat: invariant for sector activation fix

---

builtin/v12/check.go
builtin/v12/init/invariants.go
builtin/v13/check.go
builtin/v13/init/invariants.go

@ZenGround0 already fixed this in #188, but they got brought into v12/v13 accidentally.

feat: remove incorrect invariants

---

builtin/v10/migration/init.go
builtin/v10/migration/system.go
builtin/v11/migration/miner.go
builtin/v11/migration/power.go
builtin/v11/migration/system.go
builtin/v12/migration/miner.go
builtin/v12/migration/system.go
builtin/v13/migration/market.go
builtin/v13/migration/miner.go
builtin/v13/migration/system.go
builtin/v13/migration/top.go
migration/runner.go
migration/util.go

On top of https://github.com/filecoin-project/go-state-types/pull/236

nv22 Cached migration

---

exitcode/common.go
exitcode/names.go
exitcode/reserved.go

That way we get nicer error messages.

feat: add names for "common" errors

---

builtin/methods.go
builtin/v13/gen/gen.go
builtin/v13/market/cbor_gen.go
builtin/v13/market/market_types.go
builtin/v13/market/methods.go

Fixes https://github.com/filecoin-project/go-state-types/issues/239

feat: add SettleDealPayments method and types

---

builtin/v13/check.go
builtin/v13/market/invariants.go

These adjust the invariants to account for the changes in https://github.com/filecoin-project/FIPs/pull/950.

fix: invariants: adapt to FIP-0076 changes

---

builtin/actor_tree.go
builtin/cbor_gen.go
builtin/v10/check.go
builtin/v10/init/invariants.go
builtin/v10/migration/eam.go
builtin/v10/migration/top.go
builtin/v11/check.go
builtin/v11/init/invariants.go
builtin/v12/check.go
builtin/v12/init/invariants.go
builtin/v13/check.go
builtin/v13/init/invariants.go
builtin/v14/check.go
builtin/v14/init/invariants.go
builtin/v14/migration/top.go
migration/job.go

See https://github.com/filecoin-project/lotus/pull/12155

feat: rename Actor.Address to Actor.DelegatedAddress

---

builtin/v14/migration/top.go

The diff behind [this](https://github.com/filecoin-project/go-state-types/issues/285#issuecomment-2218337634) ~20% improvement.  See discussion starting [here](https://github.com/filecoin-project/go-state-types/issues/285#issuecomment-2213122632)

Raw code migrator

---

version.json

Release: v0.14.0

---

version.json

chore: update version to v0.15.0-rc1

chore: update version to v0.15.0-rc1

---

builtin/v16/miner/policy.go
builtin/v16/miner/policy_test.go

fip-0100: constants and function to calculate daily fee

---

builtin/v16/miner/policy.go
builtin/v16/miner/policy_test.go
network/version.go

* reduce daily_fee to 5.56e-15 / 32GiB
* add nv26 & nv27
Ref: https://github.com/filecoin-project/FIPs/discussions/1105#discussioncomment-12471015

fip-0100: proposed adjustments from feedback round

---

version.json

chore: bump version to v0.16.0-rc5

---

big/int.go
builtin/v10/power/power_state.go
builtin/v10/util/math/polyval.go
builtin/v11/power/power_state.go
builtin/v11/util/math/polyval.go
builtin/v12/power/power_state.go
builtin/v12/util/math/polyval.go
builtin/v13/power/power_state.go
builtin/v13/util/math/polyval.go
builtin/v14/power/power_state.go
builtin/v14/util/math/polyval.go
builtin/v15/power/power_state.go
builtin/v15/util/math/polyval.go
builtin/v16/power/power_state.go
builtin/v16/util/math/polyval.go
builtin/v8/power/power_state.go
builtin/v8/util/math/polyval.go
builtin/v9/power/power_state.go
builtin/v9/util/math/polyval.go

chore: fix some comments

---

version.json

chore: bump version to v0.16.0

---

builtin/v17/migration/system.go
builtin/v17/migration/top.go

feat: add simple migration nv27

---

builtin/claim.go
builtin/shared.go
builtin/v16/power/power_state.go
builtin/v17/power/power_state.go
go.mod
go.sum

This PR integrates MapReduce cache. The replace directive is temporary.
I don't like how it sits in the middle of everything but it seems like the best option.

Integrate MapReduce cache
