abi/empty.go
This comes from the `adt` (not `abi`) package in actors, but should really have been in `abi` since it features in many method signatures.
=> Add Empty type/value

rt/actor.go
Ideally, this would just be defined in lotus (where the type is used).
However, I'd like to change the `BuiltinActors()` method in specs-actors to return `[]Actor`. This way, all actors for a specific specs-actors version can be registered with the lotus vm with a single `vm.Register(..., BuiltinActors()...)` call.
Unfortunately, the type `[]actors0.Actor` is not the same as `[]actors1.Actor`, even if `actors0.Actor` and `actors1.Actor` are identical interfaces. Hence the definition in this package.
=> Add a shared actor interface definition

network/version.go
This patch adds a version 5 (pending, may change), and provides a "version count" for convenience.
=> fill in new network versions

network/version.go
Should we speculatively add 7,8,9,10 so we can save a few minutes when developing upgrades under pressure in the next few weeks?
=> Prep for upcoming upgrades

network/version.go
Network version 6 is ready to be shipped. We need new version numbers to flag specs actor changes.
=> add network versions

dline/deadline.go, dline/deadline_test.go
Previously, this would have to walk through all deadlines between the proving period start and the current epoch. That was fine for the use-case but I'd _like_ to be able to compute the next-not-elapsed deadline at a significant distance.
Obviously, this has a pretty exhaustive test case.
=> make NextNotElapsed faster

builtin/v8/market/deal.go, builtin/v8/market/deal_test.go
The new approach is to:
- marshal string-type labels as the string 
- marshal byte-type labels as the empty string
- unmarshal all labels as strings, and set them to string-type labels.
This isn't strictly correct, as a byte-type label will fail the round trip, but that is not a case we are much concerned about supporting yet.
=> Tweak JSON marshaling of labels

builtin/v8/gen/gen.go, builtin/v8/verifreg/cbor_gen.go, builtin/v8/verifreg/verified_registry_state.go
This field isn't serialized as a tuple in v8, but instead as an int. See https://github.com/filecoin-project/builtin-actors/pull/574 for more.
=> fix: verifreg: RmDcProposalID should not be a struct

builtin/v9/migration/test/parallel_migration_test.go, builtin/v9/migration/test/util.go, go.mod
Bug introduced in #46, the parallel test needs a sync blockstore.
=> Use sync blockstore for parallel migration test

builtin/v8/gen/gen.go, builtin/v8/power/cbor_gen.go, builtin/v8/power/methods.go, builtin/v8/reward/cbor_gen.go, builtin/v9/gen/gen.go, builtin/v9/init/cbor_gen.go, builtin/v9/init/init_actor_state.go, builtin/v9/market/cbor_gen.go, builtin/v9/market/market_types.go, builtin/v9/miner/cbor_gen.go, builtin/v9/miner/miner_state.go, builtin/v9/miner/policy.go, builtin/v9/power/cbor_gen.go, builtin/v9/power/methods.go, builtin/v9/reward/cbor_gen.go
[fix: v9 init state: remove InstalledActors](https://github.com/filecoin-project/go-state-types/commit/f4ad1a59d916a5e25536b7044368e503e9c16fd5)
- I think this was caused by basing the v9 state off the wrong branch of builtin-actors
[fix: v9 market types: add SectorType to SectorDeals](https://github.com/filecoin-project/go-state-types/commit/395c37ab732cccd7a18e7bb3f722c342674755ef)
- Missed in the FIP-0034 integration
[Add QAPowerMax method](https://github.com/filecoin-project/go-state-types/commit/6740cdd9390d2a252543527685a3ac51c393087f)
- Needed in clients like Lotus
[fix: MinerInfo: move benificiary terms to the right position](https://github.com/filecoin-project/go-state-types/commit/32d4e8d49c0f0cc9857b08449f9f3a9dee51d9b0)
- Bug in the FIP-0029 integration
[fix: power methods: …
=> Several v9 types fixes

builtin/v8/account/methods.go, builtin/v8/cron/methods.go, builtin/v8/init/methods.go, builtin/v8/market/methods.go, builtin/v8/miner/methods.go, builtin/v8/multisig/methods.go, builtin/v8/paych/methods.go, builtin/v8/power/methods.go, builtin/v8/reward/methods.go, builtin/v8/system/methods.go, builtin/v8/verifreg/methods.go, builtin/v9/account/methods.go, builtin/v9/cron/methods.go, builtin/v9/init/methods.go, builtin/v9/market/methods.go, builtin/v9/miner/methods.go, builtin/v9/multisig/methods.go, builtin/v9/paych/methods.go, builtin/v9/power/methods.go, builtin/v9/reward/methods.go, builtin/v9/system/methods.go, builtin/v9/verifreg/methods.go
Verifreg in actors v9 has one method with a very large method num. Cbor-gen runs out of memory trying to deal with a slice with that index, so we're making the methods structs a map.
=> fix: Make methods list a map

crypto/signature.go
A new SigType is required for sig.Verify to check the signature signed by Ethereum's clients. The reason we can't use existing SigTypeSecp256k1 is that its verifier uses blake2b to hash the message, but SigTypeDelegated's verifier should use keccak256 to hash the message, so we need a new SigType to distinguish them.
=> feat: crypto: add SigType: SigTypeDelegated

builtin/v8/market/policy.go
Thank you for pulling the types into their own package, this is excellent work!
I was looking through a codebase, and was able to replace all my uses of `github.com/filecoin-project/specs-actors` with `github.com/filecoin-project/go-state-types` ... except for this one case: https://github.com/filecoin-project/evergreen-dealer/blob/dbbaf53e90960a/cron/trackdeals.go#L219-L221
Proposing to lift `DealUpdatesInterval` into go-state-types just like it is in actors: https://github.com/filecoin-project/specs-actors/blob/v8.0.1/actors/builtin/market/policy.go#L11
=> Lift missed DealUpdatesInterval into state-types

builtin/v9/verifreg/verified_registry_state.go, builtin/v9/verifreg/verifreg_types.go
Add verifreg accessors for getting allocations and claims from the multi-HAMTs
=> Add accessors for allocation HAMT in verifreg actor

builtin/shared.go, builtin/v8/miner/deadline_state.go, builtin/v8/util/adt/set.go, builtin/v9/datacap/datacap_state.go, builtin/v9/datacap/datacap_types.go, builtin/v9/market/market_state.go, builtin/v9/market/policy.go, builtin/v9/migration/datacap.go, builtin/v9/migration/market.go, builtin/v9/migration/miner.go, builtin/v9/migration/system.go, builtin/v9/migration/test/migration_test.go, builtin/v9/migration/test/util.go, builtin/v9/migration/top.go, builtin/v9/migration/verifreg.go, builtin/v9/miner/deadline_state.go, builtin/v9/util/adt/map.go, builtin/v9/util/adt/set.go, builtin/v9/verifreg/cbor_gen.go, builtin/v9/verifreg/verified_registry_state.go, builtin/v9/verifreg/verifreg_types.go, go.mod, manifest/manifest.go
Closes #69
**The sequence of steps is:**
- Step 0: Add the DataCap actor to the v8 state tree with a fake Head
- Step 1A: Migrate all actors except the StorageMarketActor and VerifiedRegistryActor as part of the "regular" migration workflow (more details on the migrations below), set the results in the output state tree
- Step 1B: In a separate, parallel goroutine migrate the VerifiedRegistryActor, and then the StorageMarketActor
- Block on 1A and 1B
- Step 2: Set the VerifiedRegistryActor and StorageMarketActor in the output state tree
- Step 3: Flush and return
**Miner Migration**
The minerMigrator performs the following migrations:
- FIP-0029: Sets the `Beneficary` to the `Owner`, and sets empty values for `BeneficiaryTerm and PendingBeneficiaryTerm`
- FIP-0034: For each …
=> FIP-0045: Implement migrations

builtin/v9/migration/market.go, builtin/v9/migration/top.go, builtin/v9/migration/verifreg.go
Three fixes:
- Make the migration deterministic, by eliminating iterating over go maps
- Cache the datacap actor result based on the _verified registry's_ head. If this head changes we need to redo the migration, if not the cached result is good.
- Create the datacap actor in the _input_ actors tree, not output, so that it actually goes through a migration (this was a bug introduced through copypasta).
=> Make migration deterministic

builtin/v9/migration/test/migration_test.go, builtin/v9/migration/test/miner_test.go, builtin/v9/migration/verifreg.go
Outstanding issue from [here](https://github.com/filecoin-project/go-state-types/pull/85#discussion_r989550336). This now matches market actor code: https://github.com/filecoin-project/builtin-actors/blob/5934421954d63e7ec84b4ba6eaac1e30811e9a05/actors/market/src/lib.rs#L1141-L1147.
=> Tweak Verifreg migration params

builtin/singletons.go
Need the actor ID separately because we don't want to parse it from the address every time we construct a delegated address.
=> add the Ethereum Address Manager as a singleton.

builtin/v9/migration/datacap.go, builtin/v9/migration/top.go, builtin/v9/migration/util.go, builtin/v9/migration/verifreg.go
This refactors full proposal traversal to a single preliminary call that collects deal IDs of verified pending deals for verifreg migration and their total size for datacap migration
=> Add verifreg balance to datacap

builtin/v9/migration/market.go
Quoting [the FIP ](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0045.md#migration),
> Add the pending allocation mapping to market state, and claim ID field to deal states (all 0)
The second half of this direction (set claim ID field of deal states to 0) was missing. This PR adds the necessary operation.
=> Market migration: Correctly migrate deal states

builtin/v8/miner/invariants.go, builtin/v9/check.go, builtin/v9/migration/market.go, builtin/v9/miner/invariants.go
If this bitfield is too big, don't expand it, and look up values in the bitfield directly -- slower, but acceptable.
=> Invariant checks: don't expand big allocatedSectors bitfields

builtin/methods.go, builtin/v9/datacap/methods.go
Adds a missing method from the datacap actor. Corresponding `builtin-actors` PR [here](https://github.com/filecoin-project/builtin-actors/pull/795)
=> fix: Add allowance method to Datacap Actor

abi/address.go, abi/address_test.go
Currently, all addresses are valid (up to nv17). When we land the nv18 patch, we'll allow "delegated" addresses in nv18 only.
=> feat: add a method for validating an address for a network version

abi/cbor_bytes_transparent.go, builtin/v10/account/methods.go, builtin/v10/multisig/methods.go, builtin/v9/account/methods.go, builtin/v9/multisig/methods.go
Lotus needs a cbor-marshallable data type to pass in here. Both the `Account` and `Multisig` actors ignore the params passed in to `UniversalReceiverHook`, so we will pass `*abi.EmptyValue`.
=> fix: Universal Receiver method for account and verifreg take abi.EmptyValue

builtin/frc_0042.go
Updated to match the spec https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0042.md
=> fix: Allow underscore as first character for frc-0042 method names

builtin/v10/migration/system.go, builtin/v10/migration/top.go, migration/util.go
Extracts some common migration functionality out of v10. Migrates code CIDs and the system actor. Putting this here as a starting point as I already implemented it for FIPI-0047
Also adds nil address in ActorV5 which Closes https://github.com/filecoin-project/go-state-types/issues/127
=> feat: Implement barebones v10 migration

builtin/v10/migration/eam.go, builtin/v10/migration/init.go, builtin/v10/migration/top.go
- Create the EAM Actor with "empty object" head
- Create the EthZeroAddress actor as an EthAccount, map it in the init actor (without a robust address)
- everything else is just a CodeID update, and has the new `Address` field nil
=> feat: implement the v10 migration

builtin/methods.go, builtin/v10/eam/eam_types.go, builtin/v10/eam/methods.go
For changes in https://github.com/filecoin-project/builtin-actors/pull/1032
See https://github.com/filecoin-project/ref-fvm/issues/1434
=> add CreateExternal to eam

abi/cbor_bytes_transparent.go, abi/cbor_test.go
This type has always been broken, it's just never been used.
=> Fix: CborBytesTransparent: Unmarshal correctly

builtin/v10/evm/cbor_gen.go, builtin/v10/evm/evm_types.go
- brings types inline with those present in builtin-actors#dev/20230117-pre-rc.4
=> fix: match builtin-actor DelegateCallParams struct

builtin/v10/evm/evm_types.go, builtin/v10/evm/evm_types_test.go, builtin/v10/evm/methods.go
Unfortunately, this requires a manual CBOR implementation.
=> fix: EVM::GetBytecode now returns an Option

exitcode/reserved.go
=> fix: add back deprecated exit code definitions

builtin/methods.go, builtin/v10/account/methods.go, builtin/v10/ethaccount/methods.go, builtin/v11/account/methods.go, builtin/v11/ethaccount/methods.go
- It now returns a `bool` instead of just erroring on failure https://github.com/filecoin-project/builtin-actors/pull/1216
- It has been removed from EthAccounts https://github.com/filecoin-project/builtin-actors/pull/1217
=> feat: incorporate changes to AuthenticateMessage

builtin/v11/migration/miner.go, builtin/v11/migration/top.go, builtin/v11/miner/cbor_gen.go, builtin/v11/miner/miner_state.go
This PR introduces the skeleton of the nv19 migration, including a cached migration that migrates all sectors as needed by https://github.com/filecoin-project/builtin-actors/pull/1229.
Tests will be written in Lotus.
=> feat: sector migration for nv19

builtin/v10/miner/invariants.go, builtin/v11/miner/invariants.go, builtin/v9/miner/invariants.go
We are not setting this field which appears to be behind a big chunk of state invariant failures.
=> Fix invariants

builtin/v11/check.go, builtin/v11/init/invariants.go
I'm still not 100% sure its right to remove these.  They are definitely incorrect but invariant breaks of these forms are somewhat useful to see in the logs as they indicate particular edge cases that can be confirmed to not be part of the problem.  I think it's probably better to remove them for cleanliness but ideally we'd try to find a way to assert something about the edge cases.  Right now that looks either impossible or difficult hence this PR.
=> Remove incorrect invariants

builtin/sector.go
Add SyntheticPoRep to SealProofPoliciesV11 in builtin/sector.go.
These seems to be missing when we did tests on the Butterfly-network, causing extensions of SynthPoRep sector to fail with:
```
lotus-miner sectors extend 3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b987a8]
goroutine 1 [running]:
github.com/filecoin-project/lotus/chain/actors/policy.GetSectorMaxLifetime(...)
/home/misty/lotus/chain/actors/policy/policy.go:592
main.glob..func74(0xc000b46580)
/home/misty/lotus/cmd/lotus-miner/sectors.go:1194 +0xfc8
github.com/urfave/cli/v2.(*Command).Run(0xab4e160, 0xc000b46580, {0xc000b45080, 0x2, 0x2})
/home/misty/go/pkg/mod/github.com/urfave/cli/v2@v2.25.5/command.go:274 +0x9eb …
```
=> fix: Add SynthPoReps to SealProofPoliciesV11

builtin/v12/migration/miner.go, builtin/v12/miner/cbor_gen.go, builtin/v12/miner/miner_state.go
See https://github.com/filecoin-project/builtin-actors/issues/1275
and https://github.com/filecoin-project/builtin-actors/pull/1395 (most notably @ZenGround0 [comment](https://github.com/filecoin-project/builtin-actors/pull/1395#pullrequestreview-1605376348))
In short, we want to have an easily extensible flags field for the SectorOnChainInfo instead of a field per flag, which is wasteful.
=> replace SimpleQaPower with flags

builtin/v12/check.go, builtin/v12/market/cbor_gen.go, builtin/v12/market/deal.go, builtin/v12/market/invariants.go, builtin/v12/market/market_state.go, builtin/v12/migration/top.go
#210 doesn't yet include updating the market DealState schema. This PR isn't a complete resolution (I'm no longer familiar with the rest of the migration code), but intended to be cherry-picked or otherwise cloned into #210 as a prompt to migrate those objects.
See https://github.com/filecoin-project/builtin-actors/pull/1347 and https://github.com/filecoin-project/builtin-actors/pull/1403
=> Update deal state schema to match Rust

builtin/v12/market/cbor_gen.go, builtin/v12/market/deal.go, builtin/v12/market/invariants.go, builtin/v12/miner/cbor_gen.go, builtin/v12/miner/miner_types.go
- ProveCommit2Return should have a single BatchReturn field (not an array) based on actors code
- DealState adds the SectorNumber field and removes the VerifiedClaim field
=> Fix ProveCommit2Return and DealState structs in GST

builtin/v12/check.go, builtin/v12/miner/invariants.go, builtin/v12/miner/policy.go
Otherwise, we compute the wrong expected power and expected deal start times.
=> fix: invariants: use the power base epoch instead of the activation

go.mod
we accidentally skipped a tag which leads to the latest tag v0.12.7 dont have the commit https://github.com/filecoin-project/go-state-types/commit/3d83d7d8dff18d85345e1408a8b8be400058bec1 we want 
to avoid go deps confusion, we are proposing to retract the wrongfully tagged v0.12.7 and once this PR is in we will tag v0.12.8
=> clean up go tags

builtin/v13/migration/system.go, builtin/v13/migration/top.go
"Lightest" migration that updates Code IDs based on new manifest, and the state of the system actor accordingly.
=> feat: add simple nv22 migration

builtin/v13/check.go, builtin/v13/market/invariants.go, builtin/v13/miner/invariants.go
These are new invariants that cover FIP-0076 changes.
Partly extracted from #236, with additional invariants based on https://github.com/filecoin-project/builtin-actors/pull/1520.
=> feat: FIP-0076: add new invariants

builtin/v10/migration/init.go, builtin/v10/migration/system.go, builtin/v11/migration/miner.go, builtin/v11/migration/power.go, builtin/v11/migration/system.go, builtin/v12/migration/miner.go, builtin/v12/migration/system.go, builtin/v13/market/invariants.go, builtin/v13/migration/market.go, builtin/v13/migration/miner.go, builtin/v13/migration/system.go, builtin/v13/migration/top.go, builtin/v13/util/adt/map.go, builtin/v13/util/adt/map_test.go, builtin/v9/migration/test/migration_test.go, builtin/v9/migration/test/miner_test.go, builtin/v9/migration/test/parallel_migration_test.go, builtin/v9/migration/test/util.go, migration/runner.go, migration/util.go, test_util/blockstore.go
Extracted from #236.
This is a direct copy of the code from there (except for changes made in earlier PRs #245 and #244). I have not yet examined the code for correctness, nor have I addressed some outstanding review on that PR, and so am opening this as draft for now. It effectively needs review including from me.
In particular, reviewers please examine whether the use of the migration cache is incorrect if the "pre-migrated" state is NOT an ancestor of the migration input state. It SHOULD be the case that this is ancestry-agnostic.
=> feat: FIP-0076: implement migration to populate ProviderSectors

builtin/v13/migration/market.go, builtin/v13/migration/miner.go, builtin/v13/migration/top.go, migration/util.go
=> feat: make the upgrade epoch input from the client

builtin/v10/verifreg/cbor_gen.go, builtin/v10/verifreg/verifreg_types.go, builtin/v11/verifreg/cbor_gen.go, builtin/v11/verifreg/verifreg_types.go, builtin/v12/verifreg/cbor_gen.go, builtin/v12/verifreg/verifreg_types.go, builtin/v13/verifreg/cbor_gen.go, builtin/v13/verifreg/verifreg_types.go
FIP says Address, builtin-actors says ActorID for both ClaimExtensionRequest and AllocationRequest.
FIP: https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0045.md#creation-of-allocations-and-extension-of-claims-from-datacap-transfer
This mismatch has been in place since v9, but I'm not sure which way this should fall except that `AllocationRequest` has been working as an `ActorID` all this time so we probably don't want to break that.
https://github.com/filecoin-project/go-state-types/pull/76 was filled as per the request was to match builtin-actors in https://github.com/filecoin-project/go-state-types/issues/57. But this PR landed _before_ a change to builtin-actors that switched both of these from `Address` to `ActorID`: …
=> fix: make ClaimExtensionRequest provider type match builtin-actors

builtin/v13/migration/miner.go
=> fix: miner migration: only Remove sectors that we would have Added in the first place

builtin/v13/migration/top.go
This check is already happening at https://github.com/filecoin-project/go-state-types/compare/asr/test-yushi?expand=1#diff-eb78243bbcd4789a11776f71488d112dcbb5cb16e99d20100501e2a7430b4b2dR134-R136 below, we don't need to do it twice.
=> v13 migration: nit: drop redundant check

builtin/v13/migration/market.go
If we had fewer than 1000 proposals (only relevant when testing, really), we'd panic because `proposalsSize/1000 == 0` and `cnd % 0` leads to a divide by zero panic.
=> fix: fix v13 migration panic when proposals < 1000

builtin/v14/migration/system.go, builtin/v14/migration/top.go
=> feat: Add simple nv23 migration

builtin/v14/migration/top.go
I'm liking keeping this directly in top.go so it's easy to see what's going on.  I can move it if someone feels strongly though.
Testing is going to have to wait for lotus integration: https://github.com/filecoin-project/lotus/issues/11896
=> Migrate f090 to safety

builtin/v12/verifreg/verifreg_types_test.go, builtin/v13/verifreg/verifreg_types_test.go, builtin/v14/verifreg/verifreg_types_test.go
Since I was touching type changes in https://github.com/filecoin-project/go-state-types/pull/262 I thought I'd do an initial version of something I've proposed doing a more comprehensive form of: cbor encoding and round-trip testing of publicly exported types, which is particularly important for the types we pass through builtin-actors. So for now I'm just starting with  ClaimAllocationsParams, and am following this up with a PR to builtin-actors with identical fixtures.
Ideally we'd expand this, perhaps slowly, to cover the full suite of types that pass through this barrier, and in the process provide fixtures for other implementations to test against as well.
The diagnostic output might be overkill, I can remove that if someone wants to object, I just like being absolutely clear.
=> test: verifreg: add initial cbor encoding forms tests

abi/sector.go, builtin/methods.go, builtin/v14/gen/gen.go, builtin/v14/miner/cbor_gen.go, builtin/v14/miner/methods.go, builtin/v14/miner/miner_types.go, builtin/v14/miner/miner_types_test.go, builtin/v14/miner/policy.go
Params implementation and tests with vectors to match https://github.com/filecoin-project/go-state-types/pull/270
=> feat: miner: niporep params and cbor encoding vector tests

actors_version_checklist.md
Closes: #122
Update `actors_version_checklist.md` to reference Go-State-Types Checklist in Lotus repository. This will ensure that the maintenance burden for keeping this checklist up to date is kept low and the documentation remains up-to-date.
=> chore: Update `actors_version_checklist.md` to reference GST-checklist in Lotus

network/version.go
This PR updates the `TBD` codename for NetworkVersion23 in `network/version.go` to reflect that Waffle has been choosen for the codename of NV23: https://metropolis.vote/dashboard/c/6pnapz4axv.
Slack-thread asking for clarification here: https://filecoinproject.slack.com/archives/CEHTVSEG6/p1718632500744349?thread_ts=1717005618.376869&cid=CEHTVSEG6
=> chore: Update codename for NetworkVersion23

builtin/methods.go, builtin/v14/gen/gen.go, builtin/v14/miner/cbor_gen.go, builtin/v14/miner/methods.go, builtin/v14/miner/miner_types.go
This reflects the changes made in https://github.com/filecoin-project/builtin-actors/pull/1553
=> Update CSPV naming

builtin/v14/migration/top.go
It turns out we deploy butterfly net with an account actor.  In such a case the migration passes because we don't check f090's pre migration code cid, just set its code cid post migration.  The problem that arises with this is that the delegated address is kept in state which allows sends to continue working after the migration.
This PR isn't critical for mainnet state since in mainnet f090 is a multisig with delegated address == nil.  So there could be no such spending post migration.  However its cleaner to follow the f099 path and set delegated address to the id address of the actor.  This has the benefit of giving the expected behavior on testnetworks that want to set up f090 as both a large canonical store of FIL and an account actor.
=> Set f090 delegated address to f090

builtin/v14/migration/top.go
Because it is an account actor on Butterfly and Calibnet and is used as the faucet.
=> FIP-0085: Only migrate f090 if it is a multisig

builtin/v13/check.go
I encountered both these errors when running the invariant-check on mainnet. Deleting these two invariants given that they existed only to test the v13 migration as per the TODO in code comments.
- `"MIGRATION-ONLY: un-slashed deal %d not referenced in active sectors of miner %v", dealID, deal.Provider"`
- `"MIGRATION-ONLY: deal %d not found in miner %v for sector %v", dealID, maddr, sectorID)"`
=> chore: Cleanup invariant errors related to v13 migration

Makefile, proof/cbor_gen.go, proof/gen/gen.go
The `manifest` line in Makefile is included in #283 because it's needed to get past new linting. But `proof` is not included there and I wanted to serialise a couple of the Aggregate types in there for debugging but they don't yet have cbor-gen additions. We don't strictly need these for communication between lotus and actors, but they are handy to have for debugging!
=> chore: include manifest & proof in `make gen`; add extra proof types

builtin/v13/market/market_state.go, builtin/v13/market/policy.go, builtin/v14/market/market_state.go, builtin/v14/market/policy.go
Ref: https://github.com/filecoin-project/go-state-types/pull/237
This is the same as #237 but on top of master and with v14 included and v12 excluded.
It's a 👍 from me and @magik6k endorsed this on slack and it _possibly_ (but maybe not) addresses a live issue being experienced by lotus-miner @ https://github.com/filecoin-project/lotus/issues/12014
This apparently should have been done with the introduction of allocation term-min term-max.
As per my comment in #239 on the scope of this and what it touches:
> In actors we calculate duration the same way: https://github.com/filecoin-project/builtin-actors/blob/8d957d2901c0f2044417c268f0511324f591cb92/actors/miner/src/lib.rs#L5522-L5534
>
> This code gets used in lotus for StateMinerPreCommitDepositForPower here: …
=> fix: market: use expiry-activation for deal weight calculation

version.json
Ship a v0.15.0-dev release, which contains a network skeleton for nv24 (v15 actors)
=> Release: v0.15.0-dev

builtin/network.go, builtin/v15/miner/policy.go, builtin/v15/miner/policy_test.go
Ref: https://github.com/filecoin-project/builtin-actors/issues/1573
Ref: https://github.com/filecoin-project/builtin-actors/pull/1574
Test copied across from Rust.
This will have implications for Lotus because of the breaking API change, it'd probably be worth figuring out how much pain that is before merging this.
=> fix(miner)!: remove DEAL_WEIGHT_MULTIPLIER and its input to QAP calc

version.json
chore: bump version to v0.15.0
=> chore: bump version to v0.15.0

version.json
Publishing a v0.16.0-dev release, so that https://github.com/filecoin-project/lotus/issues/12686 can be completed/worked on.
=> chore: publish v0.16.0-dev

builtin/v9/migration/top.go, migration/runner.go
reference to https://github.com/filecoin-project/lotus/pull/12732
This pull request includes an update to the logging format in the `MigrateStateTree` function to improve clarity during the migration process.
Logging improvements:
* [`builtin/v9/migration/top.go`](diffhunk://#diff-0f71e4e5376421454dd6e1792714840e621766fb31e279de1749157bf59a8bd3L400-R405): Changed the log message to include the percentage of jobs completed and rephrased the message for better readability.
=> fix(migration): improve job progress logging in MigrateStateTree

version.json
chore: bump version to v0.16.0-rc1
=> chore: bump version to v0.16.0-rc1

builtin/v10/power/power_state.go, builtin/v11/power/power_state.go, builtin/v12/power/power_state.go, builtin/v13/power/power_state.go, builtin/v14/power/power_state.go, builtin/v15/power/power_state.go, builtin/v16/power/power_state.go, builtin/v8/power/power_state.go, builtin/v9/power/power_state.go
Currently, F3 would iterate over claims AMT, then call the `MinerNominalPowerMeetsConsensusMinimum`, which would load the same AMT again.
=> Separate out claim check to to avoid double claim load in Lotus

version.json
=> chore: bump version to v0.16.0-rc3

builtin/v10/miner/invariants.go, builtin/v10/miner/miner_state.go, builtin/v11/miner/invariants.go, builtin/v11/miner/miner_state.go, builtin/v12/miner/invariants.go, builtin/v12/miner/miner_state.go, builtin/v13/miner/invariants.go, builtin/v13/miner/miner_state.go, builtin/v14/miner/invariants.go, builtin/v14/miner/miner_state.go, builtin/v15/miner/invariants.go, builtin/v15/miner/miner_state.go, builtin/v16/gen/gen.go, builtin/v16/migration/miner.go, builtin/v16/miner/cbor_gen.go, builtin/v16/miner/invariants.go, builtin/v16/miner/miner_state.go, builtin/v16/miner/miner_types.go, builtin/v16/miner/unmarshall_test.go, builtin/v8/miner/invariants.go, builtin/v8/miner/miner_state.go, builtin/v9/miner/invariants.go, builtin/v9/miner/miner_state.go
I've also changed the `LoadVestingFunds` to return a `[]VestingFund` so we can abstract across the different underlying representations.
fixes #350
=> fip-0100: update the vesting funds types to the new layout

builtin/v16/miner/cbor_gen.go, builtin/v16/miner/deadline_state.go, builtin/v16/miner/invariants.go, builtin/v16/miner/miner_state.go, builtin/v16/miner/miner_types.go, builtin/v16/miner/miner_types_test.go, go.mod, go.sum
Needs one of https://github.com/whyrusleeping/cbor-gen/pull/111 or https://github.com/whyrusleeping/cbor-gen/pull/112 first; and this isn't complete, I have ExpirationSet and Deadline serialization tests to add to match https://github.com/filecoin-project/builtin-actors/blob/481e18161e0af9a9a076327569c4e90fccf23fb6/actors/miner/tests/types_test.rs
=> fip-0100: sectoronchaininfo, deadline and expirationset type changes

builtin/v16/miner/invariants.go
1. Verify that the fees in the expiration queues match the fees associated with the sectors for each entry in each queue.
2. Verify that the sums of the fees in all the the expiration queues for each deadline match the fees in the deadlines.
3. Verify that the sum of the partition live power matches the live power in each deadline.
=> fip-0100: add daily fee state invariants

actors/version.go
Need this to be set properly for testing the nv24->nv25->nv26 upgrade flow in integration tests.
=> chore: map nv26 (Tock) to actors version 16

builtin/v16/miner/miner_state.go
I've left the FIP0098 fields as they'll remain relevant until the upgrade. But the deal IDs are now totally dead.
=> feat(v16): avoid seralizing the deprecated deal IDs field

builtin/methods.go, builtin/v16/gen/gen.go, builtin/v16/miner/cbor_gen.go, builtin/v16/miner/miner_types.go, builtin/v16/miner/monies.go, builtin/v16/miner/monies_test.go, builtin/v16/power/cbor_gen.go, builtin/v16/power/power_types.go
See https://github.com/filecoin-project/builtin-actors/pull/1639 for the other end of this
* Added the exported actors method numbers
* Added params and return types for those methods
* Added `PledgePenaltyForContinuedFault` and `PledgePenaltyForTermination` methods and their tests that match the Rust implementation
* Removed some batch balancer left-overs
=> feat: fip-0098 types, methods etc.

version.json
Ship a v0.17.0-dev release, which contains a network skeleton for nv27.
=> Release: v0.17.0-dev

builtin/v12/gen/gen.go, builtin/v12/market/cbor_gen.go, builtin/v12/market/market_types.go, builtin/v12/market/methods.go, builtin/v13/gen/gen.go, builtin/v13/market/cbor_gen.go, builtin/v13/market/market_types.go, builtin/v13/market/methods.go, builtin/v14/gen/gen.go, builtin/v14/market/cbor_gen.go, builtin/v14/market/market_types.go, builtin/v14/market/methods.go, builtin/v15/gen/gen.go, builtin/v15/market/cbor_gen.go, builtin/v15/market/market_types.go, builtin/v15/market/methods.go, builtin/v16/gen/gen.go, builtin/v16/market/cbor_gen.go, builtin/v16/market/market_types.go, builtin/v16/market/methods.go, builtin/v17/gen/gen.go, builtin/v17/market/cbor_gen.go, builtin/v17/market/market_types.go, builtin/v17/market/methods.go
Closes: #409
From builtin-actor v12 onwards, `ActivateDeals` was replaced with 
`BatchActivateDeals`, but go-state-types was still using the old method.
This change updates all affected versions (v12–latest) to align with the
current actor API.
- Method rename: ActivateDeals -> BatchActivateDeals
- Param type change: ActivateDealsParams -> BatchActivateDealsParams
- Updated parameter structure with sector-specific fields
- Regenerated CBOR for updated params
=> Replace ActivateDeals with BatchActivateDeals and update params (v12–latest)
